[   INFO] [2018-04-28 12:06:47,914] [9296] [HTMLReport.py(94)] - 预计并发线程数：1
[   INFO] [2018-04-28 12:06:47,915] [10772] [Result.py(44)] - 开始测试： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[  DEBUG] [2018-04-28 12:06:47,935] [10772] [connectionpool.py(208)] - Starting new HTTP connection (1): 127.0.0.1
[   INFO] [2018-04-28 12:07:07,574] [13128] [HTMLReport.py(94)] - 预计并发线程数：1
[   INFO] [2018-04-28 12:07:07,575] [3184] [Result.py(44)] - 开始测试： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[  DEBUG] [2018-04-28 12:07:07,595] [3184] [connectionpool.py(208)] - Starting new HTTP connection (1): 127.0.0.1
[   INFO] [2018-04-28 12:08:04,156] [19080] [HTMLReport.py(94)] - 预计并发线程数：1
[   INFO] [2018-04-28 12:08:04,184] [15912] [Result.py(44)] - 开始测试： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[  DEBUG] [2018-04-28 12:08:04,215] [15912] [connectionpool.py(208)] - Starting new HTTP connection (1): 127.0.0.1
[  DEBUG] [2018-04-28 12:08:55,524] [10772] [connectionpool.py(396)] - http://127.0.0.1:1080 "POST http://172.16.57.170:9100/knowledge/ HTTP/1.1" 500 744
[   INFO] [2018-04-28 12:08:55,526] [10772] [Result.py(92)] - 测试执行通过： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[   INFO] [2018-04-28 12:08:55,526] [10772] [Result.py(55)] - 测试结束： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[   INFO] [2018-04-28 12:08:55,527] [10772] [Result.py(57)] - 耗时： 127.61150838484618
[   INFO] [2018-04-28 12:08:55,527] [9296] [HTMLReport.py(123)] - 
Pass	test_post_knowledge (testcase.knowledge_controller.KnowledgeController)

[   INFO] [2018-04-28 12:08:55,530] [9296] [HTMLReport.py(143)] - 
测试结束！
运行时间: 0:02:07.613261
共计执行用例数量：1
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0
[   INFO] [2018-04-28 12:08:55,530] [9296] [api_test_runner.py(30)] - 测试
[  DEBUG] [2018-04-28 12:08:55,530] [9296] [api_test_runner.py(31)] - 测试
[WARNING] [2018-04-28 12:08:55,531] [9296] [api_test_runner.py(32)] - 测试
[  ERROR] [2018-04-28 12:08:55,531] [9296] [api_test_runner.py(33)] - 测试
[CRITICAL] [2018-04-28 12:08:55,531] [9296] [api_test_runner.py(34)] - 测试
[  DEBUG] [2018-04-28 12:09:15,277] [3184] [connectionpool.py(396)] - http://127.0.0.1:1080 "POST http://172.16.57.170:9100/knowledge/ HTTP/1.1" 500 744
[   INFO] [2018-04-28 12:09:15,280] [3184] [Result.py(92)] - 测试执行通过： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[   INFO] [2018-04-28 12:09:15,281] [3184] [Result.py(55)] - 测试结束： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[   INFO] [2018-04-28 12:09:15,281] [3184] [Result.py(57)] - 耗时： 127.70616288185212
[   INFO] [2018-04-28 12:09:15,283] [13128] [HTMLReport.py(123)] - 
Pass	test_post_knowledge (testcase.knowledge_controller.KnowledgeController)

[   INFO] [2018-04-28 12:09:15,288] [13128] [HTMLReport.py(143)] - 
测试结束！
运行时间: 0:02:07.708156
共计执行用例数量：1
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0
[   INFO] [2018-04-28 12:09:15,288] [13128] [api_test_runner.py(30)] - 测试
[  DEBUG] [2018-04-28 12:09:15,289] [13128] [api_test_runner.py(31)] - 测试
[WARNING] [2018-04-28 12:09:15,289] [13128] [api_test_runner.py(32)] - 测试
[  ERROR] [2018-04-28 12:09:15,290] [13128] [api_test_runner.py(33)] - 测试
[CRITICAL] [2018-04-28 12:09:15,290] [13128] [api_test_runner.py(34)] - 测试
[  DEBUG] [2018-04-28 12:10:11,825] [15912] [connectionpool.py(396)] - http://127.0.0.1:1080 "POST http://172.16.57.170:9100/knowledge/ HTTP/1.1" 500 744
[   INFO] [2018-04-28 12:10:11,828] [15912] [Result.py(92)] - 测试执行通过： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[   INFO] [2018-04-28 12:10:11,829] [15912] [Result.py(55)] - 测试结束： test_post_knowledge (testcase.knowledge_controller.KnowledgeController)
[   INFO] [2018-04-28 12:10:11,830] [15912] [Result.py(57)] - 耗时： 127.64531856043928
[   INFO] [2018-04-28 12:10:11,831] [19080] [HTMLReport.py(123)] - 
Pass	test_post_knowledge (testcase.knowledge_controller.KnowledgeController)

[   INFO] [2018-04-28 12:10:11,836] [19080] [HTMLReport.py(143)] - 
测试结束！
运行时间: 0:02:07.675448
共计执行用例数量：1
执行成功用例数量：1
执行失败用例数量：0
跳过执行用例数量：0
产生异常用例数量：0
[   INFO] [2018-04-28 12:10:11,837] [19080] [api_test_runner.py(30)] - 测试
[  DEBUG] [2018-04-28 12:10:11,837] [19080] [api_test_runner.py(31)] - 测试
[WARNING] [2018-04-28 12:10:11,838] [19080] [api_test_runner.py(32)] - 测试
[  ERROR] [2018-04-28 12:10:11,838] [19080] [api_test_runner.py(33)] - 测试
[CRITICAL] [2018-04-28 12:10:11,839] [19080] [api_test_runner.py(34)] - 测试
